name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag merry-christmas-generator:$(date +"%d-%m-%Y")
       docker push docker.pkg.github.com/diessetechnology/merry-christmas-generator/merry-christmas-generator:$(date +"%d-%m-%Y")
